/** Render a DocsReport as Markdown (for PR comments / audit artifacts). */

import { DIMENSION_LABELS, type DocsReport, type Dimension } from "../types.js";

const ICON = { error: "✗", warning: "⚠", info: "ℹ", pass: "✓" } as const;

export function toMarkdown(report: DocsReport): string {
  const s = report.summary;
  const out: string[] = [];
  out.push(`# docsanity report`);
  out.push("");
  out.push(
    `**${s.score}/100 (${s.grade})** across **${s.pages}** page(s) — ` +
      `${s.errors} error(s), ${s.warnings} warning(s), ${s.infos} info(s)`,
  );
  out.push("");

  out.push(`| Dimension | Errors | Warnings |`);
  out.push(`| --------- | -----: | -------: |`);
  for (const dim of Object.keys(report.summary.byDimension) as Dimension[]) {
    const b = report.summary.byDimension[dim];
    out.push(`| ${DIMENSION_LABELS[dim]} | ${b.errors} | ${b.warnings} |`);
  }
  out.push("");

  for (const page of report.pages) {
    const head = `## ${page.path} — ${page.score}/100 (${page.grade})`;
    out.push(head);
    if (page.readability) {
      out.push(
        `_${page.readability.words} words · grade ${page.readability.grade.toFixed(0)} (${page.readability.gradeLabel}) · ${page.readability.ease}_`,
      );
    }
    out.push("");
    if (page.findings.length === 0) {
      out.push(`✓ No issues.`);
      out.push("");
      continue;
    }
    out.push(`| | Rule | Where | Message |`);
    out.push(`| - | ---- | ----- | ------- |`);
    for (const f of page.findings) {
      const where = f.line ? `L${f.line}` : "";
      out.push(`| ${ICON[f.severity]} | \`${f.rule}\` | ${where} | ${f.message.replace(/\|/g, "\\|")} |`);
    }
    out.push("");
  }

  out.push(`---`);
  out.push(`<sub>Generated by docsanity v${report.version} · ${report.generatedAt}</sub>`);
  out.push("");
  return out.join("\n");
}
